export const icon = {
  iconHomeActive: require('../assets/icons/icon_home_active.png'),
  iconHomeInactive: require('../assets/icons/icon_home_inactive.png'),
  iconPromoActive: require('../assets/icons/icon_promo_active.png'),
  iconPromoInactive: require('../assets/icons/icon_promo_inactive.png'),
  iconOrderActive: require('../assets/icons/icon_order_active.png'),
  iconOrderInactive: require('../assets/icons/icon_order_inactive.png'),
  iconChatActive: require('../assets/icons/icon_chat_active.png'),
  iconChatInactive: require('../assets/icons/icon_chat_inactive.png'),
  iconSearch: require('../assets/icons/icon_search.png'),
  iconUser: require('../assets/icons/icon_user.png'),
  iconGopay: require('../assets/icons/icon_gopay.png'),
  iconGopaylater2: require('../assets/icons/icon_gopaylater_2.png'),
  iconGopaycoins: require('../assets/icons/icon_gopaycoins.png'),
  iconTopup: require('../assets/icons/icon_topup.png'),
  iconPay: require('../assets/icons/icon_pay.png'),
  iconExplore: require('../assets/icons/icon_explore.png'),
};
